### ISSUE TITLE
Support needed for <script> tag

### ISSUE THREAD

**Issue by ph1oneX** [theomessin/vue-chat-scroll#112]
I am new to Vue JS and prefer script tag instead of Node or npm.

Can any body just send me a sample complete app including which and where script tag should be used?

**Comment by theomessin** [comment]
Just include 

```html
<script src="https://cdn.jsdelivr.net/npm/vue-chat-scroll/dist/vue-chat-scroll.min.js"></script>
```

after you've included Vue. Usage is the same: https://github.com/theomessin/vue-chat-scroll/tree/1.x#usage

**Comment by ph1oneX** [comment]
That's OK but can you guide me with a simple example.

**Comment by ausinetnirmal** [comment]
after adding the cdn library and adding the v-chat-scroll="{smooth: true, notSmoothOnInit: true}" it doesnt have any impact
