### ISSUE TITLE
Can't get it to work with transition-group animations

### ISSUE THREAD

**Issue by NotHolst** [theomessin/vue-chat-scroll#17]
It works for me when just using a normal `<ul>` tag, but if i use `<transition-group name="shoutbox" tag="ul">` it doesn't

**Comment by theomessin** [comment]
No idea if transition-group supports directives. Will investigate...

**Comment by MaxLyons** [comment]
Any update to this? I can't get it to work in general, or with a transition-group

**Comment by theomessin** [comment]
@MaxLyons No update on the transition-group. As far as I can tell, it can't be done (transition-group directives are not documented; no idea if they are even a thing). 

> I can't get it to work in general

Can you maybe provide any more info? Maybe open up a new issue if you can't get it to work "in general"...
