### ISSUE TITLE
Scroll bar doesn't go to bottom on route change

### ISSUE THREAD

**Issue by nowshad-sust** [theomessin/vue-chat-scroll#18]
my chat routes may change like this - /conversations#/{user_id}
It seems that the scrolling is working fine with a single chat thread.
But when changing the route, scroll bar doesn't go to the bottom.

**Comment by rakeshtinku** [comment]
i would like to work on this

**Comment by samriddhi** [comment]
Is there any update on this.?
I have a multiple chats in the same wrapper however it only works on the first on chat and not the rest of the threads that I have to  open on click,

**Comment by theomessin** [comment]
@rakeshtinku I assume you didn't get a chance to look into this?

**Comment by theomessin** [comment]
@exwizzard wanna pull request this as well?

**Comment by AbdullahGhanem** [comment]
@exwizzard can you help me to fix it my project? 
how or where can I add your code to my project?

**Comment by exwizzard** [comment]
@AbdullahGhanem I have added the code into my component that has the vue-chat-scroll directive:

```
        beforeRouteEnter (to, from, next) {
            next(vm => {
                vm.$refs.console.scroll({
                    top: vm.$refs.console.scrollHeight,
                    behavior: 'instant'
                });
            })
        },
```

**Comment by theomessin** [comment]
I'm closing this issue as it's hogging my dashboard. Feel free to re-open it once you've got a way for me to reproduce the problem locally.
