### ISSUE TITLE
how to use this programatically? or scroll on event ?

### ISSUE THREAD

**Issue by vesper8** [theomessin/vue-chat-scroll#21]
I can't get it to work in my project. When I initially load my chatrooms they are empty of messages, then another API call gets the messages and fills up the wrapper div on which v-chat-scroll is applied

I would want it to auto-scroll to the bottom at that point.. but it doesn't happen

How can I fire a "scroll to bottom" after I get the response from my api call ?

**Comment by theomessin** [comment]
Hello @vesper8 😄 Can you please provide your code? Also, do you get any errors such as ` Failed to resolve directive` or similar?

**Comment by theomessin** [comment]
Invalid until more information is provided.
