### ISSUE TITLE
Sadly it does not work for me. 

### ISSUE THREAD

**Issue by PythonLinks** [theomessin/vue-chat-scroll#23]
Here is my existing code: 

  <div v-for="message in messages" class="row animated bounceInRight">
        <div class="col-sm-12">
            <canvas width="80" height="80" data-jdenticon-hash="{{message.hash}}" class="img-thumbnail 
            img-responsive img-circle"></canvas>
            <div class="panel panel-default">
                <div class="panel-body">{{message.name}}: <span v-html="message.text"></span></div>
            </div>
        </div>
      </div>

I got it from 
https://emitter.io/develop/html5-chat/

You can see my improvements(?) at 
https://m.PythonLinks.info

I tried to get your version to work, but no luck.   The big problem is that I do not understand vue.js, so I do not really know what I am doing. 

I guess I will take a few days to read the docs, and figure out which way is up. 

Warm Regards
Christopher Lozinski

**Comment by theomessin** [comment]
This demo might help you out:
https://theomessin.github.io/vue-chat-scroll/
https://github.com/theomessin/vue-chat-scroll/blob/master/docs/index.html
