### ISSUE TITLE
el.scroll is not a function

### ISSUE THREAD

**Issue by Zippersk** [theomessin/vue-chat-scroll#27]
I am getting this error:
`TypeError: el.scroll is not a function`

Does this plugin require jQuery? If yes, it should by mentoied in readme.

**Comment by theomessin** [comment]
It shouldn't need jQuery. The demo works fine and it doesn't use jQuery. Can you confirm that the demo works for you as well (https://theomessin.github.io/vue-chat-scroll/)? Can you provide more info (such as browser, version, etc.)?

**Comment by Zippersk** [comment]
I want use this plugin in combination with [electron](https://electronjs.org), but i seems that the version of chromium in electron doesn't have scroll function. 

```
> document.body.scroll
undefined

```
But when i tried it in normal browser :
```
>document.body.scroll
ƒ scroll() { [native code] }
```

So this error is probably caused by electron...
I thought it is jquery function, because i can not find any documentation on documentElement.scroll function. I just found documentation of [jQuery function](https://www.w3schools.com/jquery/event_scroll.asp).

**Comment by GwonHyeok** [comment]
@Zippersk 
I have a same problem. but now i solved the problem by use scroll polyfill library.

[https://github.com/iamdustan/smoothscroll](scroll polyfill - smoothscroll)
