### ISSUE TITLE
Scroll methos does not support in Internet explorer 11

### ISSUE THREAD

**Issue by premwebdeveloper** [theomessin/vue-chat-scroll#28]
I have developed a chat app in laravel and vue js with pusher. It's working proper in all browers but internet explorer is not supporting scroll method. I have installed v-chat-scroll library for scrolling.

Below mentioned errors occuring in console
[Vue warn]: Error in directive chat-scroll inserted hook: "TypeError: Object doesn't support property or method 'scroll'"

Object doesn't support property or method 'scroll'

var scrollToBottom = function scrollToBottom(el, smooth) {
  el.scroll({
    top: el.scrollHeight,
    behavior: smooth ? 'smooth' : 'instant'
  });

Here is my package.json file

{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^5.0.1",
    "jquery": "^3.1.1",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "laravel-echo": "^1.4.0",
    "pusher-js": "^4.2.2",
    "v-toaster": "^1.0.3",
    "vue-chat-scroll": "^1.3.3"
  }
}

**Comment by theomessin** [comment]
Who uses IE these days? I'll leave this issue open for a bit but I won't be fixing this.

**Comment by yellowiscool** [comment]
I hate IE probably as much as you do, but sometimes you just have to support it. I might do a pull-request when I will stop crying.

**Comment by theomessin** [comment]
:+1: Feel free to do a pull request!
