### ISSUE TITLE
Scroll on page load

### ISSUE THREAD

**Issue by RMK147** [theomessin/vue-chat-scroll#3]
Hello,

Just another issue I've come across, would it be possible to make the div scroll to the bottom on page load, as I am now showing some older messages.

Thanks.

**Comment by theomessin** [comment]
This one's pretty easy. Had it done for my project. Will add it in the next release!

**Comment by theomessin** [comment]
4f177120188f97d50712a9ebef8a0a23deef49f8

**Comment by theomessin** [comment]
See first full release ;)

a08258dc917c04435e4165486a84834001d80718
