### ISSUE TITLE
Make it working with disappearing elements

### ISSUE THREAD

**Issue by christophrumpel** [theomessin/vue-chat-scroll#30]
Hey, first thanks for this package. I am using for my chat interface and mostly it works great.
A problem I have is when I use a `typing indicator`(animated bubble). It is shown while messages are coming in but it disappears afterward. I think this change conflicts with your package because the scrolling is wrong now. It scrolls further down that it should be, resulting in some whitespace under the last message. When I move the mouse, then it automatically scrolls up, realizing there is nothing after the last message. Do you know of any solution to get this working for me?

**Here are some images explaining my case:**

1. Showing typing indicator
![screenshot1](http://tests.nomoreencore.com/github-images/chat1.png)

2. Showing wrong scroll position
![screenshot1](http://tests.nomoreencore.com/github-images/chat2.png)

3. Showing correct scroll position after I move the mouse
![screenshot1](http://tests.nomoreencore.com/github-images/chat3.png)

**Comment by theomessin** [comment]
That's an interesting bug. Let me see what I can do...

**Comment by christophrumpel** [comment]
Hey @theomessin , just wanted to mention that I use now a custom solution because there are too many things happen in my chat and I need to be more in control of where and how to scroll. Still thanks.
