### ISSUE TITLE
How to change style of message

### ISSUE THREAD

**Issue by duythang** [theomessin/vue-chat-scroll#31]
Hello @theomessin 

Thank you for your nice component
Now i am trying to use your component for my chat app.
I want to change style  of message inside chat box. In my case,
i want sender and receiver message style are different. 
Can you let me know how can i do it ?

Thank you so much

**Comment by theomessin** [comment]
Hi @duythang. Vue-chat-scroll has no control over the rendering of elements, such as styling of messages. You can change everything using CSS in your component, but that has nothing to do with this plugin.
