### ISSUE TITLE
Edge does not support el.scroll

### ISSUE THREAD

**Issue by kieraneglin** [theomessin/vue-chat-scroll#32]
In the `scrollToBottom` method, there is a call to `el.scroll`.  When `el` is an `Element`, it works fine on Chrome and Firefox but not on Edge.

I'm not sure the root cause of this, but I believe `el.scroll` should be avoided entirely.  Edge throws an error, but I don't see `scroll` in `Element`'s properties whatsoever: https://developer.mozilla.org/en-US/docs/Web/API/Element

Replacing `scroll` with a documented method like `scrollTop` would likely increase compatibility.

**Comment by theomessin** [comment]
If I remember correctly I used to have scrollTop but we changed over to scroll to support smooth scrolling (see #22). Could probably check the browser and fallback to scrollTop if scroll isn't found.

**Comment by theomessin** [comment]
@kieraneglin I am on Linux so it's very difficult for me to test this. I believe I've fixed the issue but you please confirm this for me (using latest version `1.3.4`)?

**Comment by theomessin** [comment]
I'll assume that #6a26c4363d3395fe126c46deb5a5cb18fbc4cb11 fixed this. Feel free to re-open the issue if this is not the case.

**Comment by kieraneglin** [comment]
@theomessin Seems to work!  Thank you 💪
