### ISSUE TITLE
Can't get it to work in Firefox

### ISSUE THREAD

**Issue by johnRivs** [theomessin/vue-chat-scroll#33]
Works in Chrome though.

Firefox: 62.0.3 (64-bit)
vue: 2.5.17
vue-chat-scroll: 1.3.3

When I load the page, the container is just as big as the total amount of messages in chat, exceeding the viewport. No scrollbar appears. I'm using the readme.md example with `{ always: false }`.

**Comment by theomessin** [comment]
This doesn't actually have to do anything with the plugin but the demo, right?

**Comment by theomessin** [comment]
Or, this has to do with your implementation. Make sure you've got a max-height set to your div, or it will just grow to match its content.

**Comment by johnRivs** [comment]
Guess I'll apply max-height only on Firefox. Thanks!
