### ISSUE TITLE
If I open multiple chat window div it scroll always the first one unnecessarily

### ISSUE THREAD

**Issue by hkmsadek** [theomessin/vue-chat-scroll#38]
I have a facebook like chat system. When I open new chat window, it always scroll again the first window. But it works for all chat window if I send message. Another problem is, how can I scroll by default at the bottom of the div without needing to send a new message? Is there any way to apply this scroll programmatically? It seems, scrolling is applied in updated/watch that's why when data changes it runs. I am not sure. :) 
Thank you

**Comment by hkmsadek** [comment]
I am using it like this 

```
<div class="chatbox focus" @click="chatFcoused(index)" v-if="activeChatUsers.length" v-for="(u, index) in activeChatUsers" :key="index">
   <div class="chatbox-main " v-if="u.chatType!='order'">
      <div class="chatbox-two" :id="`box${u.user_id}`" v-chat-scroll="{always: true, smooth: true}">
         <div v-if="u.msg.length" v-for="(m, index) in u.msg" :key="index">
         </div>
      </div>
   </div>
</div>
```

This loops has effect with one another. If I close the chat window other chat window start scrolling or moves up instead of stay at bottom. 

Thank you for the reply

**Comment by theomessin** [comment]
I can't really help you with just that :slightly_frowning_face: Can you send me the entire component so I can try reproducing this and start tinkering with it? Even better would be the bare minimum code needed to reproduce this issue.

**Comment by theomessin** [comment]
If someone can reproduce this in a simple repo (jsfiddle-like) then I might be able to do something. I don't have the time to basically debug someone else's website. Closing for now
