### ISSUE TITLE
vue-chat-scroll is scrolling to the wrong position

### ISSUE THREAD

**Issue by kperveen** [theomessin/vue-chat-scroll#39]
I have the following structure
```
<div class="messages">
   <div class="s-box" v-chat-scroll>
        <v-component v-for="m in messages"/>
   </div>
</div>

.messages {
 display: flex;
 flex: auto;
 flex-direction: column;
}

s-box {
 margin-top: auto;
}

```

when I use this code, the wrapper's scroll scrolls to the correct position and scroll to a wrong position, its this because of the component used?

**Comment by theomessin** [comment]
A way to reproduce the bug (JSFiddle will do) makes my life so much easier and the chances of me fixing this triple. I can only assume that this is due to your component. Can't do much out without a way of reproducing this.
