### ISSUE TITLE
Scroll position isn't taking into consideration image heights

### ISSUE THREAD

**Issue by codepotato** [theomessin/vue-chat-scroll#40]
I've noticed what I think is a weird issue to do with images. 

I'm using this in a messaging service and have noticed that it'll scroll to the correct location when all messages are text based, but when messages contain images the scroll position is wrong. 

I can only assume this is because it's not taking into consideration the height of the images as these are loading when calcs are run?

**Comment by focux** [comment]
I was about to post the same. I'm having the same issue when having images in the chat.

**Comment by theomessin** [comment]
I'll see what I can do.

**Comment by focux** [comment]
This bug is because of loading image with unknown height. The only workaround I found for this was to set a fixed height for every img.
