### ISSUE TITLE
Scroll on button click

### ISSUE THREAD

**Issue by Sequoya42** [theomessin/vue-chat-scroll#41]
I used the scroll for a chat.
The chat contains a v-data-table (vuetify), with pagination.
Clicking on the pagination while on the middle of the page, scroll to bottom. 
(which I didn't want).
I added a 
```js
if (e[0].target.tagName === "BUTTON") {
        return;
      }
```

inside the scroll directive mutationObserver to deal with it. [be able to interact with an inner element without scrolling].
To specify the issue : 
It happens on mouseDown, so the pagination does not take effect, and the page just scroll to bottom.

I guess there might be a better way to handle those kind of things?

Regards,

**Comment by theomessin** [comment]
Your solution seems reasonable enough. Makes sense that the mutation observer fires when the table inside the chat changes, could maybe find a way to better filter legit mutations that require a scroll to bottom. For now you can stick with your fix. If more people think this is an issue then we'll see!
