### ISSUE TITLE
addEventListener is not removed on unbind

### ISSUE THREAD

**Issue by sebmor** [theomessin/vue-chat-scroll#52]
although most modern browsers automatically destroy it, older browsers won't and it will cause a memory leak.
ideally we call removeEventListener on unbind in the directive

**Comment by theomessin** [comment]
AFAIK browsers that don't clean up after event listeners don't support MutationObserver you don't really have to worry about this. Either way, will fix.

**Comment by theomessin** [comment]
Feel free to submit a PR. I feel this is not needed though.
