### ISSUE TITLE
Add event when top of scrollbar is reached

### ISSUE THREAD

**Issue by alex-w0** [theomessin/vue-chat-scroll#55]
**Is your feature request related to a problem? Please describe.**
When a client is entering my chat, I'm only showing to him the recent messages. If he would like to see now also further messages, then he needs to scroll up to the beginning, where further should be fetched asynchronously.

**Describe the solution you'd like**
An event would be nice that is automatically triggered when user scrolls up and reaches the top of the scrollbar

**Comment by theomessin** [comment]
Great idea! Would you to submit a PR?

**Comment by alex-w0** [comment]
Sure, here you have https://github.com/theomessin/vue-chat-scroll/pull/56
How can I link this issue with the pull request?

The event only works when the option always is set to false, otherwise it will jump when new items will be prepended.
Would be nice if you can implement in this repository a small example page, so it would be easier for others to make pull requests.

**Comment by theomessin** [comment]
https://github.com/theomessin/vue-chat-scroll/releases/tag/v1.4.0
