### ISSUE TITLE
UglifyJs Unexpected Token >

### ISSUE THREAD

**Issue by Async0x42** [theomessin/vue-chat-scroll#6]
After importing vue-chat-scroll, uglifyjs fails in webpack with the following error:
```
ERROR in js/vendor.3b917c2.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [js/vendor.3b917c2.js:202508,27]
```
It still runs properly, but it's not able to process it, resulting in huge file sizes.

**Comment by theomessin** [comment]
Which version of UglifyJS are you using?

**Comment by Async0x42** [comment]
I'm using webpack 2.2.1 (with uglifyjs in the config) and babel to convert it, would either of those affect it?

**Comment by theomessin** [comment]
Could you please check your `package.json` and find the version of ***uglify*** (not webpack in general)

eg. in the `package.json` snippet below, uglify version is 2.7.5 or above...
```json
...
"uglify-js": "^2.7.5",
"webpack": "^2.2.0",
...
```

**Comment by Async0x42** [comment]
Webpack is pulling it in as a dependency, version 2.7.5:

yarn.lock
```
uglify-js@2.7.x, uglify-js@^2.6, uglify-js@^2.7.5:
  version "2.7.5"
  resolved "https://registry.yarnpkg.com/uglify-js/-/uglify-js-2.7.5.tgz#4612c0c7baaee2ba7c487de4904ae122079f2ca8"
  dependencies:
    async "~0.2.6"
    source-map "~0.5.1"
    uglify-to-browserify "~1.0.0"
    yargs "~3.10.0"
```

**Comment by theomessin** [comment]
Could you attach your `webpack.config.js` and your `package.json` files. I'm going to try to replicate this issue locally in hope of fixing it 😃

**Comment by Async0x42** [comment]
My webpack config has a number of files, so I'll set up a test repo for you to make it easier, I'll add another comment w/ link when it's ready

**Comment by rjscully** [comment]
I have a very plain installation with Laravel 5.4 which uses laravel-mix and this same error occurs during `npm run production` - Unfortunately I'm quite unfamiliar with the ecosystem. Everything works without vue-chat-scroll, which works in dev config but not production when uglifyJS is called:

```
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                    7:21:03 PM


 error 

js/app.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/vue-chat-scroll/src/directives/v-chat-scroll.js:8,0][js/app.js:60835,27]
```

v-chat-scroll.js line 8 is:
`const scrollToBottom = el => {el.scrollTop = el.scrollHeight;}`

So it appears to be a problem with transpiling. I tried to tinker with babel, added a .babelrc and tried to see if other babel preset packages would help but nothing has worked.

Since I haven't made changes in node_modules or really any project config I assume this will happen with a default install under Windows. When I uninstall vue-chat-scroll and remove the code referencing it, the production config works without errors.

**Comment by theomessin** [comment]
Yes, I have identified the problem. Basically, UglifyJS cannot work with ECMAScript 6. If it passes through babel first then it should work. I'll try changing the code to be ECMAScript 5 compliant and see if that fixes the issue...

**Comment by rjscully** [comment]
Thanks! It's comforting to know it wasn't something I missed, wish I were familiar enough with JS to be of any assistance :(

**Comment by theomessin** [comment]
Could you please try updating to v1.0.2 and trying to run `npm run production` and see if it works now?

**Comment by rjscully** [comment]
I got 1.0.3 and it passed that point but failed on line 14 of the same file:
`let timeout;`

`SyntaxError: Unexpected token: name (timeout)`

**Comment by theomessin** [comment]
Please try `1.0.2`

**Comment by rjscully** [comment]
Same as above for 1.0.2

**Comment by theomessin** [comment]
Okay thanks. Let me try something else... Gimme 5'

**Comment by theomessin** [comment]
Okay, try `v1.0.5` please 😄

**Comment by rjscully** [comment]
hmm are you sure 1.0.5 is available? I only see up to 1.0.4

**Comment by theomessin** [comment]
Yes, sorry `1.0.4`

**Comment by rjscully** [comment]
hurray!

**Comment by theomessin** [comment]
This works, however, it is merely a workaround. The underlying UglifyJS issue is still a problem 😕 https://github.com/mishoo/UglifyJS2/issues/448

**Comment by theomessin** [comment]
c9cb1c0a5d4658ad53ae16e13fd5388d4af159cd

**Comment by rjscully** [comment]
Yeah I saw that about UglifyJS but it seems the "solution" most people accept is transpiling first. I'm not very frontend-savvy but it seems like a major pain in the butt.

Thanks again for the workaround!
