### ISSUE TITLE
Keep focus on previous item when prepending items to the list

### ISSUE THREAD

**Issue by alex-w0** [theomessin/vue-chat-scroll#68]
**Is your feature request related to a problem? Please describe.**
Last week I've created the pull request for the event @v-chat-scroll-top-reached, which works fine.
When I'm prepending new items to the list, then the position of the scrollbar still remains on top.
Instead the focus should be kept on the previous item that was on top.

Do you have suggestions how we can solve this problem?

**Comment by theomessin** [comment]
Hi Alex. I'm not too sure what you mean by this. Could you create a quick fiddle to reproduce this and we'll go from there? You may use this [demo fiddle](https://jsfiddle.net/theomessin/n7542hk1/) as a baseline. Thanks :smiley:

**Comment by alex-w0** [comment]
@theomessin Hi Theodore, of course, here is the fiddle: https://jsfiddle.net/584ufysj/2/
I'm adding a lot of messages at the same time and it basically skips all the messages between "Message 1: The point of this vue directive..." and "New Message 9: lorem ipsum". 

Instead, they should be chronologically scrollable, which means when the messages are added the client should see first the message "New Message 0: lorem ipsum" and scrolls up to see the rest of it.

**Comment by theomessin** [comment]
I see now. Yeah that makes sense. We'll have to think how we can go about implementing this.
If you've got any ideas feel free to submit a PR.

**Comment by alex-w0** [comment]
I have already tried it a bit, but havn't yet come to any promising solution.

**Comment by weeliem** [comment]
I am facing this issue too, anyone can help?

_Moderation edit: no need to comment if you agree, a simple :+1: will suffice._

**Comment by theomessin** [comment]
I've come up with a solution I'll be implementing in the alpha channel. Stay tuned :wink: 

Will basically have a sticky option that keeps the scroll window constant even if items are prepended. All you have to do is activate this flag if the scroll position is `top` (they'll be a way to subscribe to scroll state updates in alpha).

**Comment by theomessin** [comment]
@alex-w0 @weeliem So here's what I've got working from the alpha: https://jsfiddle.net/theomessin/zhjdm0qb/

If you scroll to the top, it'll load new messages but the view should remain where it was. In practise this will be achieved by enabling the `prepending` config flag when prepending items (which will be when top is reached - not part of the alpha yet but will be eventually). Take a look and see if it suits your needs

**Comment by weeliem** [comment]
yea @theomessin nicely done, this is what i want. Hope to have this feature enabled in the next version :) Thanks.

**Comment by alex-w0** [comment]
@theomessin Great job, works really well, thanks :) Do you have committed somewhere this feature? I'm just curious how you did it.

**Comment by theomessin** [comment]
I'll get a PR with this for v2.0.0-alpha tonight. 

It's not the most high-performance implementation but it works nicely I think. For each Mutation (eventually this will probably be a ResizeMutation see #72)  we keep the scrollHeight in a WeakMap. When prepending, we scroll so that scrollTop is the difference in heights (ie. we scroll back where we were). I'll probably add a flag to disable saving the height as it does incur a performance penalty that some users might want to avoid.

**Comment by theomessin** [comment]
@alex-w0 @weeliem wouldn't mind some feedback on this implementation. Here's the same fiddle using the `v2.0.0-alpha.4`https://jsfiddle.net/theomessin/2Lm613pd/2/

If happy with this, we can go ahead and close this issue.

**Comment by weeliem** [comment]
@theomessin yea, tested and working fine :) Thanks a lot for the add-on.

**Comment by theomessin** [comment]
Feel free to re-open this issue if there are any problems.
