### ISSUE TITLE
Folder "dist"

### ISSUE THREAD

**Issue by MCMatters** [theomessin/vue-chat-scroll#7]
Why do you hide this folder from "npm"? I can't use your plugin with your instructions.
Any help will be appreciated. Thanks

**Comment by theomessin** [comment]
Basically, if you're gonna use npm I just assumed that you will use some sort of bundling software, such as webpack, to include the `vue-chat-scroll.js` file in the `src` directory.

**Comment by theomessin** [comment]
See release `1.1.0`
