### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by papersaltserver** [theomessin/vue-chat-scroll#73]
**Describe the bug**
See demo link leads to a 404 page

**To Reproduce**
1. Go to 'https://github.com/theomessin/vue-chat-scroll'
2. Click on 'See demo'
4. See error 404

**Expected behavior**
A page with a demo displayed

**Comment by theomessin** [comment]
This is due to v2 development. The repo description link has been updated to https://jsfiddle.net/theomessin/n7542hk1/. Feel free to submit a PR to update the 1.x readme.

**Comment by theomessin** [comment]
Fixed a4a305a4044d528f3a04afbafd0152d4d1cee8fc
