### ISSUE TITLE
How to debug if it is loaded?

### ISSUE THREAD

**Issue by inspire22** [theomessin/vue-chat-scroll#79]
**Describe the bug**
I'm pretty new to vue, sorry.  

I've included this in my package.json then in my main.js after importing vue:
import VueChatScroll from "vue-chat-scroll";
Vue.use(VueChatScroll);

`In my component I use <ul v-chat-scroll class="mt2">`

When I load the page and my ul has enough messages to require scrolling, no scroll happens.

Any tips how to see if it was loaded properly?  The only thing I could think of is using v-chat-scroll="true" in the html instead and making sure that property wasn't set in the result (it wasn't).  I have the vue chrome devtools addon and poked around some but couldn't see anything.

There's no console logs or errors.

Also - I *either* Vue.use(VueChatScroll) OR include the script in my index.html, right?  I tried including the script as well and nothing still happened.  There's no vue js script linked in there though.  I used the CDN script since I couldn't figure out how to get /dist/vue-chat-scroll.js to work properly via the "npm serve" server (it would just load my app when I tried to access it)

Thanks!

**Comment by theomessin** [comment]
Hi @inspire22, sorry to hear you're having issues with vue-chat-scroll. Can you please specify the versions of vue and vue-chat-scroll you're using? Also, can you confirm whether the issue is that the plugin doesn't scroll on init, or whether the plugin doesn't work at all (ie. have you tried adding items to the container to see if it scrolls?).

**Comment by inspire22** [comment]
Thanks!  My package.json has:
"vue-chat-scroll": "^1.4.0",
"vue": "^2.6.11",

Everything scrolls like it did before adding the module .  Adding and removing items via the vue dev tools setting $vm0 and adding to the data element there doesn't make it move to the bottom.  I can't even tell if it's loaded - are directives or Vue.use() things loaded anywhere into $vm0 that I could try to inspect them?

**Comment by theomessin** [comment]
If you're running this in development (ie. you can use vue browser tools) and the directive was not "loaded" you'd get an error such as:
```
[Vue warn]: Failed to resolve directive: chat-scroll
```

Currently, there's no other way to debug this. If you give me something I can reproduce (a fiddle or your code) I could maybe help debug that....

**Comment by inspire22** [comment]
Thanks!  Any way to tell if it's attached to the div that should be auto-scrolling?  Does it have to be a UL > LI like in the examples, or any subelements work?

If using the Vue.use() you don't also need the javascript include, right?

**Comment by theomessin** [comment]
Currently there's no way to debug this unless you change the package's source code (feel free to). You can use any element as long as it's scrollable (make sure the element is actually scrollable - `el.scrollHeight` **must** be greater than `el.clientHeight`). Finally, you either need the `<script>` tag or `Vue.use`, not both.

**Comment by inspire22** [comment]
I think my problem is that I'm using ionic, and they do some pretty strange stuff with shadow dom and scrollable elements - https://ionicframework.com/docs/api/content

I'll probably have to implement my own thing unfortunately.

Thanks for your help!

**Comment by inspire22** [comment]
I'm able to get access to the shadowroot scrolling element with $vm0.$refs.msg_list.shadowRoot.children[0]  -  scrollHeight & clientHeight & scrollTop all work from it - any suggestions how to get the vue directive to connect from inside my mounted() block?
