### ISSUE TITLE
When i scroll up the chat and send the message it will stay in the position where it was

### ISSUE THREAD

**Issue by ghost** [theomessin/vue-chat-scroll#82]
**Procedure of getting problem in scroll**
when i open the chat and scroll up and send the message the scroll stay in the position it was .
result needed .
if we scroll up and if we send the message without scrolling chat to bottom . the chat doen't scroll to the bottom automaticall .
if i switch from one chatroom to another chatroom as well the chat is not scrolling to buttom . it is sticking where is stop scrolled
@theomessin sir , is there any solution for it

**Comment by theomessin** [comment]
I'm sorry, I'm having trouble understanding what you're on about.
Do me a favour and resubmit this using the bug report template:

```md
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

```
