### ISSUE TITLE
@v-chat-scroll-top-reached not working

### ISSUE THREAD

**Issue by deoracle** [theomessin/vue-chat-scroll#84]
**Describe the bug**
When scroll reach to the top @v-chat-scroll-top-reached event must trigger. But its not working

<v-list
        v-chat-scroll="{ always: false, smooth: true }"
        @v-chat-scroll-top-reached="customMethod"
        class="overflow-y-auto"
        height="500"
        
      >
methods: {
    customMethod() {
      console.log('reach');
    
    },

**Comment by theomessin** [comment]
Try again using the standard bug report template please:
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. You MUST include versions of the package, vue, and browser.
```

**Comment by dioncodes** [comment]
This is also not working in my case after upgrading to the 2.0.0 alpha. On the last stable release it was working just fine. The event is not triggered at all anymore. In current Firefox / Firefox Developer Edition.

**Comment by theomessin** [comment]
@dioncodes this event has not been implemented in version 2 just yet.
